os: osx
osx_image: xcode11.3
language: objective-c
branches:
  only:
    - master
env:
  global:
    - NODE_VERSION=12.18.0
    - secure: g4OJqXjpPJ/Ojk+tHvdc/8e3RFDtpBtQMhSfz31y0khLtA8X+oyHyE0eKSbbRHb59s/LzWL213GOovfIGTAr3NVyJLa2vC2oXtcDVMqffbUrRrDxMsiam2aeiMe5k0fZIs6vWhoYvm5ImvhaFN1qQU6C9knw/yQKkG93c06amaRn9GMivC0mOtP3izaqKHmH7D41hXKQgK4CT4nR87wq99xsT168GNz3Gvdruz8Jy8BC4ajQYQg/e4Fv64OESQukQiBQs94z6ZXv4ux1Rcrcv5UeYB6wMr1QFq0DqqZb0jfzgGkCUUVzjV1eZCxMbyUbjobRNDtJcDl7XfEjTyruE7zzwJ/2DZ/uXlr9yovSWKKAHCtR/P0CaOetG3qS2XivPzGGerOXvpUm1dtXrCBLqZotXmR+0N4pKxKPAa0/cbJJr6tKkIWJzDNIfs0MXbLbrU0XCTxFiQsq19EcjDQfNhIuMlPW7xPQeQ6jGF5BibFiQHzJ44WzUNcenliytqKuXnOLAexX6L15eZnWF/gkbbY15elMHywGGQwGTsTmUOjg572OCf4SKE+ekGADG+YKZdeoYbpQMiCXjV8dtEjb+5iUc2UmlCUlGATqfFZWPxbjudquzVj3xLa7mxZopN7irsuJLGwDueKWg2PVl9gXce/BDTQAj0XRW8ydFxuu9AY=
    - secure: CACoC8mdokKIBV60hQBDegDpPqXpfHAIOxSqm05MzhBiTlZBuSW4Tly06G4Dq55h6X0CE5TAyIvxqc0wJauMyJqX2I+HGxZH/66yNu+DldUxa0n+kwcRtochGMHCWND+ZJaasGiZSSeot4VqKgQosxxC+Q7X8pv9UljMs3stlyU3WP+3B/3aHQhwA5DZhCP1eEofgt/6bw3AuE1eIsMfW/jbARbuIVc8cXddJvQEfrPF7hbPZFX+TFlINKPmOOFm1b0SuQlHJLNrwwnAYHGylHMda921PjKT1uUJCP/LfLAlY9p0UgfmueOSj8aMdC1Z/M3PodyOdHsl4pqp3xxz+JmhxGIu+LtsTbP8YattB8ZjOgdRZD5ZBgOlETYSGXXI2zd9zSfBZT7jTMN4xTtSdoWvrOESpyLm0LDOo1WbtynAqWhvacXJGDmRYDE5J1vCyCSkcw9obSGoTbw5WBGNKQYfvixynRz2rh+BXL1vMrfLZPyPjurp4iyaHV+zXLCQMTLEtAFI5E0XbPva7e6bzzJbZmemXMe6qUURKz2SkWQvI8bO6Xtljz0WSt07eF9to4uVKKgdEp4XoqbGejJy98sSnv2CA0RkLy8K/8NxeRpqoYNW4YHYxwyUz/QzmXhJ64A3kwkXABewX57n4pqk4pBf3ihSjQ9Go85kpHCNK68=
    - secure: TqzrHRoVM1b7p2jSH3QPFs3bW8SrUXgut53ODtQWwDQXbWSivfd6mf4COBMZNRSuopWs+UQVSCiZNquiuDJjwIihaa2ZTsSF9cBJpKa5rno7q0PzjcUNkbeyF+eFWi06HL7Kzdr8Cm76ihfkRgCOlxxQZJVjSFJf4ErXqTgRPzH7aYSV3mmNy8w73Wxl5F6wY7bfLKSQhnGHOcYMUsooHI2+vcJwiYhJ+KPjia3tyflUS0T341+Z6AbICnfhsBlaOuPXjEdLAfj7ssUR2JZLy2Y/LM3OZLrHvy1x4lIlGfNvWW3ju5A1u5ptY0LssPBorKYApCcttive9pnqqTdkz1Fb/UHIVDaptM1QHFsptvMt7wfkYQ6qq2ucDe+y18LSWHsihVM2Da9DysX1dIsGI+om2NvxYRG9GhYDsY11grXp8wN2L2vLK8+vLLCn395dGTrJapvR5CjRg/F3ToGPPTjB0LRGuuSHIeO7laP+G3aOJGB8QEwyy7gRcDbs+awtKbepNA+CqS8d7HHC1KG6jagrN1D0jsFGTc5TZBOvFSSwqUSe9KN42okMRk150RW5LHH9TDxc9AczdfJrpYC1lwqXoyK80JrGvzutDEV4eQK2G5dtJF51/wwL5Du0XZJNaz6oYQlU7/QAZzY0DzZHJoNx9MO5Z4ORer2Dv85vNOY=
install:
  # - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  # - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  # - nvm install $NODE_VERSION
  # - nvm use $NODE_VERSION
  # - nvm alias default $NODE_VERSION
  # - npm install -g yarn
  - brew install chamber
  - pip install awscli --upgrade --user
  # - npm install -g appcenter-cli
script:
  # - yarn install
  # - yarn test
  - cd ios
  # - pod install
  - bundle install
  - fastlane setup
  - fastlane certificates
