os: osx
osx_image: xcode11.3
language: objective-c
branches:
  only:
    - master
env:
  global:
    - NODE_VERSION=12.18.0
    - secure: g4OJqXjpPJ/Ojk+tHvdc/8e3RFDtpBtQMhSfz31y0khLtA8X+oyHyE0eKSbbRHb59s/LzWL213GOovfIGTAr3NVyJLa2vC2oXtcDVMqffbUrRrDxMsiam2aeiMe5k0fZIs6vWhoYvm5ImvhaFN1qQU6C9knw/yQKkG93c06amaRn9GMivC0mOtP3izaqKHmH7D41hXKQgK4CT4nR87wq99xsT168GNz3Gvdruz8Jy8BC4ajQYQg/e4Fv64OESQukQiBQs94z6ZXv4ux1Rcrcv5UeYB6wMr1QFq0DqqZb0jfzgGkCUUVzjV1eZCxMbyUbjobRNDtJcDl7XfEjTyruE7zzwJ/2DZ/uXlr9yovSWKKAHCtR/P0CaOetG3qS2XivPzGGerOXvpUm1dtXrCBLqZotXmR+0N4pKxKPAa0/cbJJr6tKkIWJzDNIfs0MXbLbrU0XCTxFiQsq19EcjDQfNhIuMlPW7xPQeQ6jGF5BibFiQHzJ44WzUNcenliytqKuXnOLAexX6L15eZnWF/gkbbY15elMHywGGQwGTsTmUOjg572OCf4SKE+ekGADG+YKZdeoYbpQMiCXjV8dtEjb+5iUc2UmlCUlGATqfFZWPxbjudquzVj3xLa7mxZopN7irsuJLGwDueKWg2PVl9gXce/BDTQAj0XRW8ydFxuu9AY=
    - secure: Yj994cRLT3PJO1Gf191wLXin5IbkR4AGTeGXI6fiv0e5UA6U/qjh6YqqeR+YiYWxZMKcziYIbVnt5QR75lupzseC2r1TqnH2Vy46PBkuwcYehXtlO211NK1BE93jLYmSOGGj7GR6HZ/FzPs4UwDR2YHeDlStBBNqvWFVO6uKXvdjWt9eyViANywxU7HBiKP/HNyV2uBP/aZvwVoe1fLvAqI73ooDjKRlhRSyZpBP/w3IUTgrxTssMbEhH1OHBXLYLru6EEAJ7WXgUPDV+xvrr1KiPRtczGAyiS5rjJ7aKUghv2E8fE+yozVVs40+bnvnTzi4y7wd6GdAmKQA0qIQ1BQKvh8KcVfuUD744IjpULCot2eBN9Cm4P1R/zi6d9R9W90q/fW890Xi2P3DpIfzH5kPpxtsENtq5y9UWlGBvFEVQgwaIAw/Rb4GcAzX7ods/OVEX19Sw4XppAFqs5Cqq5Si+LajrISLcLaJIdPYWQGdZAwegryvWqHAtqYPrNbuSxwoFkEQjlVeHTxlmgwr7N7LuxS8ACmkPq6IQVeosDnnfHAci+rPuGiRJc2SaktNZqhl9i9Myo6emDjUQrDdLgyyz+sO6xu7WFyn2znr9S6AkiVwNQoWhvCJPsVVCQbA5DNWr6LPu6SSy4LGub2/kTHqlka/IQNEHsXF61Xw0DQ=
    - secure: JtoPIlptzTtN/ph6dzgXjPLXzlKTYF7RLhSsF8r8pMkYTMA81VFTILO4soIX0C4K1CE1dKvrEXqnrnYd2iHqcON4IFDptNfnP9nCpNqaiMiIVPQv/FHuHdwTzc7n9pjf4JECe/bArj7DK+lGZyZrljwTmJQUtXl0NlgOxC0NZ7fpj5CJvqseAlvcZTnEVrs/toFUmY8eiM9DZpFLn/imS89lPi/1Tz6eq6Pz1wPDiUfBoY+GloYJFS1hQDVOgrJGx5YzKvt5rptue0IH0+jqT3hTr1I3G8VAs60PubY+NAr2jzyGdSK1OcnO7hX+65UObrr2MghGwsJL1PST13+Ps+rebxWKPwN3F0j7jgxNvJfHf2tWoYSdVDoPEwgjQlEwC7oFtQ95Hc72Kb1T8fmrcPg0hTeD9rRNwUJSBMtvMeKjqk0IH3/2EGg9NSqQXTZ83BNy70v4yw/KCHIwGWRAfvPMAsCRbmqZGaKlwTKevQWYF9O8IkoXeWbXhg/77sCYD7D8heU79us5vf2VZ3zfz6sg3BmOyN0IJcGiemeWhG1gx4BNiG3zsWblI1sg2bT8fhwg4Nn3PXxJVev12TLL3oYJZBpCyWroCf5s5usrO5xCqlJplqpS4jFSBlnA7MlXjZuQDR93F4SJL88y6tFC6YbyiTgcVAr4wrmvoy7mdUc=
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION
  - npm install -g yarn
  - brew install chamber
  - sudo apt-get install -y chamber
  - pip install awscli --upgrade --user
  - npm install -g appcenter-cli
script:
  - yarn install
  - yarn test
  - cd ios
  - pod install
  - bundle install
  - fastlane setup
  - fastlane certificates
  # - appcenter login --token $CODEPUSH_ACCESS_KEY
  # - appcenter codepush release-react -a "ysong028/WordGame" -m -t '*' --description 'Travis'
  # - appcenter logout
