# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Load environment variables"
  lane :setup do
    load_env
  end

  desc "create keychain for sigining certs"
  lane :keychain do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: is_ci,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
  end

  desc "Retrieve and resync certificates"
  lane :certificates do
    match(type: 'development', readonly: is_ci)
    # match(type: 'appstore', readonly: is_ci)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: 'appstore', readonly: is_ci)
    increment_build_number(xcodeproj: "WordGame.xcodeproj")
    build_app(workspace: "WordGame.xcworkspace", scheme: "WordGame")  
    upload_to_testflight(api_key_path: 'fastlane/appstore.json')
  end
end
